import 'package:project_mobile/data/models/produto_model.dart';

class ProdutosRepository {
  static List<ProdutoModel> listaProdutos = [
    ProdutoModel(
      id: '1',
      nome: 'Coca-Cola Lata',
      preco: 4.0,
      descricao: '350ml',
      imagem: 'coca_cola_350.png',
      categoria: CategoriaProduto.Bebida,
    ),
    ProdutoModel(
      id: '2',
      nome: 'Tempura de Legumes',
      preco: 12.50,
      descricao: 'Porção',
      imagem: 'tempura_de_legumes.jpg',
      categoria: CategoriaProduto.Lanche,
    ),
    ProdutoModel(
      id: '3',
      nome: 'Sashimi de Salmão',
      preco: 18.75,
      descricao: 'Porção',
      imagem: 'sashimi.jpg',
      categoria: CategoriaProduto.Sushi,
    ),
    ProdutoModel(
      id: '4',
      nome: 'Mochi de Morango',
      preco: 8.99,
      descricao: 'Porção',
      imagem: 'mochi.jpg',
      categoria: CategoriaProduto.Sobremesa,
    ),
    ProdutoModel(
      id: '5',
      nome: 'Hambúrguer',
      preco: 15.99,
      descricao: 'Porção',
      imagem: 'hamburguer.jpg',
      categoria: CategoriaProduto.Refeicao,
    ),
    ProdutoModel(
      id: '6',
      nome: 'Água Mineral',
      preco: 2.50,
      descricao: '500ml',
      imagem: 'agua.png',
      categoria: CategoriaProduto.Bebida,
    ),
    ProdutoModel(
      id: '7',
      nome: 'Cheesecake de Morango',
      preco: 10.50,
      descricao: 'Fatia',
      imagem: 'cheesecake_morango.jpg',
      categoria: CategoriaProduto.Sobremesa,
    ),
    ProdutoModel(
      id: '8',
      nome: 'Cone de Sorvete de Chocolate',
      preco: 5.99,
      descricao: 'sorvete',
      imagem: 'sorvete_chocolate.jpg',
      categoria: CategoriaProduto.Sorvete,
    ),
    ProdutoModel(
      id: '9',
      nome: 'Pizza de Pepperoni',
      preco: 22.99,
      descricao: 'Pizza Inteira',
      imagem: 'pizza_pepperoni.jpg',
      categoria: CategoriaProduto.Refeicao,
    ),
    ProdutoModel(
      id: '10',
      nome: 'Suco de Laranja Natural',
      preco: 4.50,
      descricao: '300ml',
      imagem: 'suco_laranja.jpg',
      categoria: CategoriaProduto.Bebida,
    ),
    ProdutoModel(
      id: '11',
      nome: 'Sanduíche de Frango Grelhado',
      preco: 11.99,
      descricao: 'Porção',
      imagem: 'sanduiche_frango_grelhado.png',
      categoria: CategoriaProduto.Lanche,
    ),
    ProdutoModel(
      id: '12',
      nome: 'Brownie de Chocolate',
      preco: 7.99,
      descricao: 'Porção',
      imagem: 'brownie.jpg',
      categoria: CategoriaProduto.Sobremesa,
    ),
    ProdutoModel(
      id: '13',
      nome: 'Temaki de Atum',
      preco: 14.25,
      descricao: 'Porção',
      imagem: 'temaki_atum.jpg',
      categoria: CategoriaProduto.Sushi,
    ),
    ProdutoModel(
      id: '14',
      nome: 'Creme de Baunilha',
      preco: 6.99,
      descricao: 'sorvete',
      imagem: 'sorvete_creme.jpg',
      categoria: CategoriaProduto.Sorvete,
    ),
    ProdutoModel(
      id: '15',
      nome: 'Yakissoba de Frango',
      preco: 17.50,
      descricao: 'Porção',
      imagem: 'yakissoba_frango.jpeg',
      categoria: CategoriaProduto.Refeicao,
    ),
  ];
}
