// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC0eHFIRSP0Rsb4V79wA8GyigytEebxzw',
    appId: '1:141959032622:web:e63f92a7cc5bbce97994bf',
    messagingSenderId: '141959032622',
    projectId: 'foodapp-c396c',
    authDomain: 'foodapp-c396c.firebaseapp.com',
    storageBucket: 'foodapp-c396c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQBn6le_-lObiPyI-PlJXI6p_9IaZ1tk',
    appId: '1:141959032622:android:94605e843755b81b7994bf',
    messagingSenderId: '141959032622',
    projectId: 'foodapp-c396c',
    storageBucket: 'foodapp-c396c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fGK-p8mDpfBSWB-kwBzwJdWzzWMz3iM',
    appId: '1:141959032622:ios:0169bdbe25d88b067994bf',
    messagingSenderId: '141959032622',
    projectId: 'foodapp-c396c',
    storageBucket: 'foodapp-c396c.appspot.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC0eHFIRSP0Rsb4V79wA8GyigytEebxzw',
    appId: '1:141959032622:web:d3ac6825d3bb51327994bf',
    messagingSenderId: '141959032622',
    projectId: 'foodapp-c396c',
    authDomain: 'foodapp-c396c.firebaseapp.com',
    storageBucket: 'foodapp-c396c.appspot.com',
  );
}
